// Auto-generated by src/quantize.py. Do not edit by hand.
#pragma once
#include <cstddef>
#include <cstdint>

alignas(8) extern const unsigned char g_ppo_model_data[];
extern const int g_ppo_model_data_len;
