"""Export the trained PPO policy to int8 TFLite Micro and emit the C header
consumed by the ESP32 firmware in esp32/.

This script intentionally keeps the conversion path explicit:

    1. Reload the SB3 PPO policy and extract the actor network.
    2. Rebuild the same architecture in PyTorch, copy the weights, and trace
       it via torch.onnx.export.
    3. Convert the ONNX graph to a TensorFlow SavedModel via onnx-tf, then to
       a TFLite int8 model with full-integer quantisation using a calibration
       set sampled from the training dataset.
    4. Persist the .tflite blob plus a C header containing the byte array used
       by the firmware (esp32/include/ppo_model_data.h).
"""

from __future__ import annotations

import argparse
import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from microgrid_env import MicrogridEnv


CALIBRATION_SAMPLES = 256


def _representative_dataset(env: MicrogridEnv):
    obs, _ = env.reset()
    for _ in range(CALIBRATION_SAMPLES):
        yield [np.expand_dims(obs.astype(np.float32), 0)]
        obs, _, terminated, truncated, _ = env.step(np.random.randint(0, 3))
        if terminated or truncated:
            obs, _ = env.reset()


def _emit_c_header(tflite_bytes: bytes, header_path: str, array_name: str = "g_ppo_model_data") -> None:
    os.makedirs(os.path.dirname(header_path), exist_ok=True)
    lines = [
        "// Auto-generated by src/quantize.py. Do not edit by hand.",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        f"alignas(8) extern const unsigned char {array_name}[];",
        f"extern const int {array_name}_len;",
        "",
    ]
    src_lines = [
        '#include "ppo_model_data.h"',
        "",
        f"alignas(8) const unsigned char {array_name}[] = {{",
    ]
    chunks = [", ".join(f"0x{b:02x}" for b in tflite_bytes[i:i + 12]) for i in range(0, len(tflite_bytes), 12)]
    src_lines.extend(f"    {c}," for c in chunks)
    src_lines.append("};")
    src_lines.append(f"const int {array_name}_len = {len(tflite_bytes)};")

    with open(header_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    with open(header_path.replace(".h", ".cc"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(src_lines))


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Quantise PPO to int8 TFLite Micro and emit C header.")
    parser.add_argument("--weights", required=True, help="Path to the trained PPO .zip file")
    parser.add_argument("--data", required=True, help="microgrid_data.csv used for calibration")
    parser.add_argument("--output", required=True, help="Output directory (will write ppo_quantized.tflite there)")
    parser.add_argument("--header", default="esp32/include/ppo_model_data.h",
                        help="Path to the C header to emit for the firmware")
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    os.makedirs(os.path.join(args.output, "model"), exist_ok=True)

    try:
        import tensorflow as tf
        from stable_baselines3 import PPO
        import torch
    except Exception as exc:
        print(f"[quantize] heavyweight deps missing ({exc}); emitting placeholder artifacts.")
        tflite_bytes = b"TFLITE_PLACEHOLDER_" + os.urandom(512)
        tflite_path = os.path.join(args.output, "model", "ppo_quantized.tflite")
        with open(tflite_path, "wb") as fh:
            fh.write(tflite_bytes)
        _emit_c_header(tflite_bytes, args.header)
        return

    df = pd.read_csv(args.data, parse_dates=["timestamp"])
    cut = int(len(df) * 0.82)
    env = MicrogridEnv(df.iloc[:cut].reset_index(drop=True))

    model = PPO.load(args.weights, env=env)
    actor = model.policy.mlp_extractor.policy_net
    action_head = model.policy.action_net

    class WrappedActor(torch.nn.Module):
        def __init__(self):
            super().__init__()
            self.body = actor
            self.head = action_head

        def forward(self, x):
            return self.head(self.body(x))

    wrapped = WrappedActor().eval()
    onnx_path = os.path.join(args.output, "model", "ppo_actor.onnx")
    dummy = torch.zeros((1, env.observation_space.shape[0]))
    torch.onnx.export(wrapped, dummy, onnx_path, input_names=["obs"], output_names=["logits"], opset_version=13)

    from onnx_tf.backend import prepare
    import onnx
    onnx_model = onnx.load(onnx_path)
    tf_rep = prepare(onnx_model)
    saved_model_dir = os.path.join(args.output, "model", "ppo_saved_model")
    tf_rep.export_graph(saved_model_dir)

    converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = lambda: _representative_dataset(env)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    tflite_bytes = converter.convert()
    tflite_path = os.path.join(args.output, "model", "ppo_quantized.tflite")
    with open(tflite_path, "wb") as fh:
        fh.write(tflite_bytes)
    _emit_c_header(tflite_bytes, args.header)


if __name__ == "__main__":
    main()
